name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
      uses: actions/cache@v2
      id: go-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Test
      run: make test
